language: go
sudo: required

go:
  - 1.x

services:
  - docker

before_install:
  - docker pull redis:alpine
  - docker run -p 6379:6379 -d redis:alpine

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - make test
